version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: llm_platform_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: llm_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "9001:5432"
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    container_name: llm_platform_redis
    ports:
      - "9002:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: llm_platform_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@llm-platform.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9003:80"
    depends_on:
      - postgres
    restart: unless-stopped
    
volumes:
  postgres_data:
  redis_data: